apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    app: {{ include "myapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 5000
        env:
          - name: MYSQL_HOST
            value: "{{ .Values.mysql.host }}"
          - name: MYSQL_USER
            value: "{{ .Values.mysql.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.mysql.password }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.mysql.database }}"
